/// Design tokens for Dojo Marketplace.
///
/// THIS FILE IS A PLACEHOLDER. In production, it will be generated by
/// Style Dictionary from `packages/tokens/tokens.json`.
///
/// Run `cd packages/tokens && npm run build` to regenerate.
library;

import 'dart:ui';

abstract final class DojoTokens {
  // Brand colors
  static const Color brandPrimary = Color(0xFFC980FC);
  static const Color brandSecondary = Color(0xFFFF7151);
  static const Color brandAccent = Color(0xFF9B59B6);
  static const Color brandWarning = Color(0xFFF4AE22);
  static const Color brandError = Color(0xFFE54C12);
  static const Color brandSuccess = Color(0xFF2E7D32);

  // Typography families
  static const String fontPrimary = 'SpaceGrotesk';
  static const String fontHeader = 'Outfit';
  static const String fontTertiary = 'Inter';

  // Motion durations (milliseconds)
  static const int durationShort = 150;
  static const int durationMedium = 200;
  static const int durationLong = 300;
}
